# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0004_auto_20171110_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='power',
            field=models.PositiveIntegerField(blank=True, help_text='Available power in Watts', null=True),
        ),
    ]
