# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0005_cabinet_power'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabinet',
            name='power',
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='asset_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID in external asset database, if any.', null=True),
        ),
        migrations.AlterField(
            model_name='powerdistributionunit',
            name='asset_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID in external asset database, if any.', null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='asset_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID in external asset database, if any.', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='portassignment',
            unique_together=set([('device', 'device_port')]),
        ),
        migrations.AlterUniqueTogether(
            name='server',
            unique_together=set([('manufacturer', 'model', 'serial')]),
        ),
    ]
