# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0006_auto_20171110_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkdevice',
            name='asset_tag',
            field=models.CharField(blank=True, help_text='Asset tag, if any.', max_length=128),
        ),
        migrations.AlterField(
            model_name='powerdistributionunit',
            name='asset_tag',
            field=models.CharField(blank=True, help_text='Asset tag, if any.', max_length=128),
        ),
        migrations.AlterField(
            model_name='server',
            name='asset_tag',
            field=models.CharField(blank=True, help_text='Asset tag, if any.', max_length=128),
        ),
    ]
