# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0007_auto_20171110_2150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cabinet',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='datacenter',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='cabinet',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='datacenter',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='powerdistributionunit',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='server',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='datacenter',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
