# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0010_auto_20171111_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkdevice',
            name='asset_id',
            field=models.CharField(blank=True, help_text='ID in external asset database, if any.', max_length=64, default=''),
        ),
        migrations.AlterField(
            model_name='powerdistributionunit',
            name='asset_id',
            field=models.CharField(blank=True, help_text='ID in external asset database, if any.', max_length=64, default=''),
        ),
        migrations.AlterField(
            model_name='server',
            name='asset_id',
            field=models.CharField(blank=True, default='', help_text='ID in external asset database, if any.', max_length=64),
            preserve_default=False,
        ),
    ]
