# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 02:56
from __future__ import unicode_literals

from django.db import migrations
import mountaineer.core.models
import mountaineer.core.utils.slug


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0012_auto_20171112_0132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SlugTestModel',
        ),
        migrations.AlterModelOptions(
            name='cabinet',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cabinetassignment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='datacenter',
            options={},
        ),
        migrations.RemoveField(
            model_name='cabinet',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='cabinetassignment',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='datacenter',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='portassignment',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='powerdistributionunit',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='server',
            name='uuid',
        ),
        migrations.AddField(
            model_name='cabinet',
            name='slug',
            field=mountaineer.core.models.SlugField(db_index=True, default=mountaineer.core.utils.slug.slugid_nice, editable=False),
        ),
        migrations.AddField(
            model_name='cabinetassignment',
            name='slug',
            field=mountaineer.core.models.SlugField(db_index=True, default=mountaineer.core.utils.slug.slugid_nice, editable=False),
        ),
        migrations.AddField(
            model_name='datacenter',
            name='slug',
            field=mountaineer.core.models.SlugField(db_index=True, default=mountaineer.core.utils.slug.slugid_nice, editable=False),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='slug',
            field=mountaineer.core.models.SlugField(db_index=True, default=mountaineer.core.utils.slug.slugid_nice, editable=False),
        ),
        migrations.AddField(
            model_name='portassignment',
            name='slug',
            field=mountaineer.core.models.SlugField(db_index=True, default=mountaineer.core.utils.slug.slugid_nice, editable=False),
        ),
        migrations.AddField(
            model_name='powerdistributionunit',
            name='slug',
            field=mountaineer.core.models.SlugField(db_index=True, default=mountaineer.core.utils.slug.slugid_nice, editable=False),
        ),
        migrations.AddField(
            model_name='server',
            name='slug',
            field=mountaineer.core.models.SlugField(db_index=True, default=mountaineer.core.utils.slug.slugid_nice, editable=False),
        ),
    ]
