# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import enumfields.fields
import mountaineer.hardware


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0013_auto_20171112_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='attachment',
            field=enumfields.fields.EnumIntegerField(blank=True, enum=mountaineer.hardware.CabinetAttachmentMethod, help_text='Hardware attachment method', null=True),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='depth',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Distance from front to rear post (inches)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='fasteners',
            field=enumfields.fields.EnumIntegerField(blank=True, enum=mountaineer.hardware.CabinetFastener, help_text='Hardware fasteners in use', null=True),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Width (inches, usually 19.0)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='posts',
            field=models.PositiveIntegerField(help_text='Number of posts in the rack (usually 4, sometimes 2)'),
        ),
    ]
