# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkdevice',
            name='asset_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID in external asset database, if any.', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='powerdistributionunit',
            name='asset_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID in external asset database, if any.', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='asset_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID in external asset database, if any.', null=True, unique=True),
        ),
    ]
