# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_auto_20171110_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkdevice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='name',
        ),
        migrations.RemoveField(
            model_name='powerdistributionunit',
            name='description',
        ),
        migrations.RemoveField(
            model_name='powerdistributionunit',
            name='name',
        ),
        migrations.RemoveField(
            model_name='server',
            name='description',
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='draw',
            field=models.PositiveIntegerField(blank=True, help_text='Power draw of the device, in Watts', null=True),
        ),
        migrations.AddField(
            model_name='powerdistributionunit',
            name='draw',
            field=models.PositiveIntegerField(blank=True, help_text='Power draw of the device, in Watts', null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='draw',
            field=models.PositiveIntegerField(blank=True, help_text='Power draw of the device, in Watts', null=True),
        ),
        migrations.AlterField(
            model_name='cabinetassignment',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.Device', unique=True),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='device',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='hardware.Device'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='manufacturer',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='model',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='rack_units',
            field=models.IntegerField(blank=True, help_text='Height of the device, in Rack Units', null=True),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='serial',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='powerdistributionunit',
            name='amps',
            field=models.PositiveIntegerField(help_text='Rated output amperage'),
        ),
        migrations.AlterField(
            model_name='powerdistributionunit',
            name='device',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='hardware.Device'),
        ),
        migrations.AlterField(
            model_name='powerdistributionunit',
            name='manufacturer',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='powerdistributionunit',
            name='model',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='powerdistributionunit',
            name='rack_units',
            field=models.IntegerField(blank=True, help_text='Height of the device, in Rack Units', null=True),
        ),
        migrations.AlterField(
            model_name='powerdistributionunit',
            name='serial',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='powerdistributionunit',
            name='volts',
            field=models.PositiveIntegerField(help_text='Rated output voltage'),
        ),
        migrations.AlterField(
            model_name='server',
            name='device',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='hardware.Device'),
        ),
        migrations.AlterField(
            model_name='server',
            name='manufacturer',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='server',
            name='model',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='server',
            name='rack_units',
            field=models.IntegerField(blank=True, help_text='Height of the device, in Rack Units', null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='serial',
            field=models.CharField(max_length=256),
        ),
    ]
