# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0003_auto_20171110_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinetassignment',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hardware.Device'),
        ),
    ]
