# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0008_auto_20171111_0257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cabinetassignment',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='cabinetassignment',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='portassignment',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
