# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import environty.core.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0011_auto_20171111_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlugTestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', environty.core.models.SlugField(db_index=True, default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='asset_id',
            field=models.CharField(blank=True, help_text='ID in external asset database, if any.', max_length=64),
        ),
        migrations.AlterField(
            model_name='powerdistributionunit',
            name='asset_id',
            field=models.CharField(blank=True, help_text='ID in external asset database, if any.', max_length=64),
        ),
    ]
